### ISSUE TITLE
POST Issue

### ISSUE THREAD

**Issue by jscoulter** [littleearth/delphiXERO#4]
Hi.
I have hit an issue where when I do a POST it tells me I am not Autherised and returns a 401 error.
GET works fine, its just POST that does it. Any ideas what I might be? Or any code updates?

Thanks :-)

**Comment by CFTechno** [comment]
Having the same problem. 

Looks like XERO doesn't care about the autorisation header for the GET but for the POST it has to be 100% correct.

As far as I can see the autorisation basestring is not constructed correctly and hence the POST fails. I checked the signature and it's correct. So it's the basestring construction and some encoding issues.

**Comment by jscoulter** [comment]
yeah I have been doing a bit of investigation and I found if I set the parameter that contains the JSON string to be posted to empty, it seems to be ok and I get a different error - that I would have expected. So I think you are on the right path there :-) I would be keen to know if you get it resolved....

**Comment by CFTechno** [comment]
The GET will work with JSON or XML but the POST will not work with JSON but will work with XML.  I did had to change a few things to get that working, made a XERO.API.XML (TXEROApiXML) version of the XERO.API.JSON (TXEROApiJSON) 

If exactly the same XML call is made with JSON (and the correct headers etc) then XERO will keep complaining, while the same call with XML will work. So that's why I moved over to using XML

The most important change is to remove 
```
    if assigned(AParams) then
      params.Assign(AParams);
```
from OAuthSignRequest in XERO.API, this line will add the JSON or XML to the basestring before it's being signed and that should not happen.

also in the same unit in the .POST function change
`    HTTPClient.HTTPOptions := [hoForceEncodeParams];`
into
`    HTTPClient.HTTPOptions := [];`

otherwise your XML or JSON gets encoded which is also not what you want :)

and in XERO.API,JSON or XERO.API.XML in the .POST function change
`      AResponse := LResponse.ReadString(LResponse.Size);`
into
`      AResponse := LResponse.Datastring;`
to make sure that the response from XERO is available

**Comment by jscoulter** [comment]
Ok. I tried a couple of those things too, but didnt think about trying XML. I will give it a crack! :-) Thanks

**Comment by jscoulter** [comment]
Woops I missed the part where you said you made the new XML unit.
I will have a go at writing the XML one. :-)  Thanks,

**Comment by CFTechno** [comment]
only two changes besides the name change, change rtjson in rtxml and it's done :)

**Comment by jscoulter** [comment]
hmm...I am still getting an authorization error. ugh....

**Comment by CFTechno** [comment]
I used HTTP debugger to watch the call and patching parts of the call to see what should be changed to make it work.  Also downloaded the official XERO C# lib and the demo to make sure that there was a baseline that was working. Comparing the two calls made it possible to find the differences.

Currently rewriting delphiXERO into a smaller lib that would also install in other versions of Delphi.

**Comment by jscoulter** [comment]
I also took a look at the ChilKat stuff and that works as expected with JSON, but really want to keep it in Delphi and not worry about extra libraries.
I might take a look at the HTTP Debugger and do what you did to see if I can get something working.

**Comment by CFTechno** [comment]
if you would use the http debugger for the chilkat then it would allow you to see the call difference. If I find some time today I'll give that a try. Do you have an exe with chilkat that posts json?

**Comment by jscoulter** [comment]
I did a bit of an investigation uses HTTP Debugger and have put the information for each POST of JSON data in the attached file. I didnt see much of a diff.....but you might see something :-)
[XeroLog.txt](https://github.com/littleearth/delphiXERO/files/3169743/XeroLog.txt)

**Comment by CFTechno** [comment]
- chilkat doesn't send the realm part of the authorization header. I also had that part removed
- chilkat has another order in the authorization header, something i also changed in delphixero

**Comment by CFTechno** [comment]
- also note that the delphixero is sending http1.0 and not http1.1

**Comment by jscoulter** [comment]
yeah I noticed the 1.1/1.0 thing but I figured that it might be Indy doing it. I will try the above too.

**Comment by jscoulter** [comment]
hi. would it be pos to get a copy of your Xero.API file? I seem to be missing something..... :-(

**Comment by mkranga** [comment]
hi. have any update about this?

**Comment by jscoulter** [comment]
I havent heard any more and ran out of time to try and get it working. I
ended up using Chilkat to keep things moving but still REALLY want to use
pure Delphi code rather then Chilkat.
Jeremy

**Comment by CFTechno** [comment]
After some changes it will work,  also trying to make one version that works with ICS. If done I'll release both versions

**Comment by CFTechno** [comment]
don't have time to fork so will do it like this :)

[XERO.API.txt](https://github.com/littleearth/delphiXERO/files/3224639/XERO.API.txt)

**Comment by CFTechno** [comment]
also added the function 
`    function OAuthSignRequestHdr(const aMethod: string; const AURL: string;
      const AConsumerKey: string; const AToken: string;
      const APrivateKey: string):String;
`

that can be used to get the correct header if using ICS like this
`   
SslHttpCLi.URL:=XERO_API_BASE_URL+'organisations';
   SslHttpCli.RcvdStream := TStringStream.Create('',Tencoding.UTF8);
   SslHttpCli.Accept :='application.xml';
   SslHttpCli.Agent := AppName;
   SslHttpCli.Get;
   response := TStringStream(SslHttpCli.RcvdStream).datastring;
`

`
procedure TfrmMain.SslHttpCliBeforeHeaderSend(Sender: TObject; const Method: string; Headers: TStrings);
var
  XEROAPI : TXEROAPIBase;
begin
   XEROAPI := TXEROAPIBase.Create;
   Headers.Add('Authorization:'+
   XEROApi.OAuthSignRequestHdr(Method, SslHttpCli.URL,
            ConsumerKey, ConsumerKey,
            PrivateKey));
   FreeAndNil(XEROAPI)
end;
`

**Comment by littleearth** [comment]
This should be resolve with the new OAuth2 as headers are different and only require a bearer token
