### ISSUE TITLE
Project XERODemo raised exception class EIdOSSLUnderlyingCryptoError 

### ISSUE THREAD

**Issue by stevenwangc** [littleearth/delphiXERO#9]
Open the project delphiXERO in Delphi 12.01, it compiles and run successfully. Key in client Id and click authenticate button, consent page displays. 
![Screenshot 2024-06-20 065214](https://github.com/littleearth/delphiXERO/assets/170482230/27b2afd3-c4c2-418d-9c9f-12699b999fe1)

Click on "Allow access for 30 minutes"

Project XERODemo.exe raised exception class EIdOSSLUnderlyingCryptoError 
with message 'Error connecting with SSL. error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocalk version';
![Screenshot 2024-06-20 065420](https://github.com/littleearth/delphiXERO/assets/170482230/c41605e3-5968-4618-a0ff-3f786d79fcbd)

please help to fix this error message

**Comment by littleearth** [comment]
Thanks, I have not yet given 12.0 a test. I will get it installed and try it out.

**Comment by stevenwangc** [comment]
@littleearth The ssl version on my computer is 1.0.0d, change the the ssl version to 1.0.2u. it works perfect fine

**Comment by littleearth** [comment]
Great Thanks for the update
